<a href="https://colab.research.google.com/github/90splayer/Applied-ML/blob/main/Week02_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1 (a) Initialise a tensor of shape 3 × 3 filled with random floats between 0
and 1.
(b) Convert this tensor to a NumPy array.
(c) Convert the NumPy array back to a PyTorch tensor

In [5]:
import torch
import numpy as np
torch.manual_seed(42) # Setting the seed
x = torch.rand(3, 3) # Creates a tensor of shape [3, 3]
np_arr = x.numpy()
tensor = torch.from_numpy(np_arr)
print(tensor)
print(tensor.dtype)
print(np_arr)
print(np_arr.dtype)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
torch.float32
[[0.88226926 0.91500396 0.38286376]
 [0.95930564 0.3904482  0.60089535]
 [0.25657248 0.7936413  0.94077146]]
float64


Q2 (a) Create two tensors A and B of shapes 2 × 3 and 3 × 2, respectively,
with random integers between 1 and 10.
(b) Perform matrix multiplication to produce tensor C = AB.
(c) Index tensor C to select its second row

In [8]:
#AN = np.random.randint(1, 11, size=(2, 3))
A = torch.randint(1, 11, (2, 3))
#BN = np.random.randint(1, 11, size=(3, 2))
B = torch.randint(1, 11, (3, 2))
C = torch.matmul(A, B)
print(A)
print(B)
print(C)
print(C[1])
#

tensor([[10,  4,  5],
        [10,  7,  3]])
tensor([[ 1,  7],
        [ 3,  8],
        [10,  8]])
tensor([[ 72, 142],
        [ 61, 150]])
tensor([ 61, 150])


Q3 (a) Create a tensor X of shape 2 × 2, filled with random floats, and
requires gradients.
(b) Define a function f (X) = P X2, and compute the gradient of f with
respect to X using backpropagation.
(c) Print the gradient of X.

In [11]:
# Create tensor with gradient tracking enabled
X = torch.randn(2, 2, requires_grad=True)

print("X:")
print(X)

X:
tensor([[-0.2935,  1.4329],
        [ 0.5312, -0.2483]], requires_grad=True)


In [16]:
# Define function
f = torch.sum(X**2)

# Backpropagation
f.backward()

In [13]:
print("Gradient of X:")
print(X.grad)

Gradient of X:
tensor([[-0.5870,  2.8657],
        [ 1.0624, -0.4965]])


Q4 (a) Check if a CUDA GPU is available with PyTorch and print a message
confirming its availability or lack thereof.
(b) Move a tensor of shape 4×4, filled with ones, to the GPU if available.

In [15]:
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)
x = torch.ones(4, 4)
x = x.to(device)
print("X", x)

Is the GPU available? False
Device cpu
X tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Q5 (a) Create a simple linear model with a single layer using PyTorch’s
neural network module.
(b) Initialise a stochastic gradient descent (SGD) optimiser for the model’s
parameters with a learning rate of 0.01.
(c) Create a dummy target tensor and compute the mean squared error
loss between the model’s output and the target.
(d) Use the optimiser to update the model’s parameters based on the
computed loss.

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

# Simple linear model: 3 inputs → 1 output
model = nn.Linear(in_features=3, out_features=1)

print(model)

Linear(in_features=3, out_features=1, bias=True)


In [18]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [19]:
# Dummy input (5 samples, 3 features)
X = torch.randn(5, 3)

# Dummy target (5 samples, 1 output)
target = torch.randn(5, 1)

# Forward pass
output = model(X)

# Mean Squared Error loss
criterion = nn.MSELoss()
loss = criterion(output, target)

print("Loss:", loss.item())

Loss: 1.3902593851089478


In [20]:
# Backprop + update
optimizer.zero_grad()
loss.backward()
optimizer.step()

print("Updated parameters:")
for param in model.parameters():
    print(param)

Updated parameters:
Parameter containing:
tensor([[-0.3954,  0.1692, -0.1828]], requires_grad=True)
Parameter containing:
tensor([0.1606], requires_grad=True)
